### ISSUE TITLE
error creating redis masters

### ISSUE THREAD

**Issue by dtenenba** [TykTechnologies/tyk-kubernetes#16]
When running the following command as described in the README:

```
$ redis-trib.py create `dig +short redis-1.redis.svc.cluster.local`:6379 \
    `dig +short redis-2.redis.svc.cluster.local`:6379 \
    `dig +short redis-3.redis.svc.cluster.local`:6379
```

I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/redis-trib.py", line 7, in <module>
    from redistrib.console import main
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 67
    command.shutdown_cluster(*_parse_host_port(addr), ignore_failed)
SyntaxError: only named arguments may follow *expression
```

I was able to make this error (and a subsequent one) go away by making the following changes to 
`/usr/local/lib/python2.7/dist-packages/redistrib/console.py`:

```diff
67c67
<     command.shutdown_cluster(*_parse_host_port(addr), ignore_failed)
---
>     command.shutdown_cluster(*_parse_host_port(addr), ignore_failed=ignore_failed)
90c90
<     command.rescue_cluster(host, port, *_parse_host_port(new_addr), max_slots)
---
>     command.rescue_cluster(host, port, *_parse_host_port(new_addr), max_slots=max_slots)
```

However, running `redis-trib.py` now I get this:

```
Redis-trib 0.6.0 Copyright (c) HunanTV Platform developers
Traceback (most recent call last):
  File "/usr/local/bin/redis-trib.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 177, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 28, in create
    command.create([_parse_host_port(hp) for hp in addrs], max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 91, in create
    t = Connection(host, port)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/connection.py", line 83, in __init__
    self._conn()
  File "/usr/local/lib/python2.7/dist-packages/redistrib/connection.py", line 68, in g
    raise RedisIOError(e, conn.host, conn.port)
redistrib.exceptions.RedisIOError: 10.110.136.80:6379 - [Errno 111] Connection refused
```

Any ideas?
Thanks...

**Comment by matiasinsaurralde** [comment]
Are you able to access your Redis instances directly? Please check the output of `dig +short redis-1.redis.svc.cluster.local`, `dig +short redis-2.redis.svc.cluster.local` and so on, then try accessing these instances using `redis-cli -h [host]`.

`redis-cli` documentation is available [here](https://redis.io/topics/rediscli).

**Comment by dtenenba** [comment]
```
root@ubuntu:/# dig +short redis-1.redis.svc.cluster.local
10.102.198.127
root@ubuntu:/# dig +short redis-2.redis.svc.cluster.local
10.100.108.167
root@ubuntu:/# redis-cli -h  redis-2.redis.svc.cluster.local
Could not connect to Redis at redis-2.redis.svc.cluster.local:6379: Network is unreachable
Could not connect to Redis at redis-2.redis.svc.cluster.local:6379: Network is unreachable
not connected>
```

This suggests the network is not set up properly?

**Comment by matiasinsaurralde** [comment]
> This suggests the network is not set up properly?

Right, suggest checking [this post](https://blog.heptio.com/configuring-your-linux-host-to-resolve-a-local-kubernetes-clusters-service-urls-a8c7bdb212a7), also [this one](https://stackoverflow.com/questions/49905482/kubernetes-not-working-with-dns-no-communication-from-pod-to-outside-world).

**Comment by dtenenba** [comment]
I'm not sure it's the same issue. I am inside the container/pod spawned by `kubectl run` and `dig` is able to resolve the DNS name. It's just that the network represented by that IP address is not reachable. I get the same errors if I use the IP address returned by `dig` instead of e.g. `redis-1.redis.svc.cluster.local`.

**Comment by matiasinsaurralde** [comment]
I see. Have you inspected the Redis pods logs?

**Comment by dtenenba** [comment]
I just tried, but it seems that the redis pods either never started or have shut down:

```
root@hdcp-c2-b2:~# kubectl --namespace=redis get pods
NAME            READY     STATUS              RESTARTS   AGE
redis-1-6cp6t   0/1       ContainerCreating   0          1h
redis-2-dgcr5   0/1       ContainerCreating   0          1h
redis-3-ssqnq   0/1       ContainerCreating   0          1h
redis-4-zlzvm   0/1       ContainerCreating   0          1h
redis-5-9jg58   0/1       ContainerCreating   0          1h
redis-6-gl8js   0/1       ContainerCreating   0          1h
root@hdcp-c2-b2:~# kubectl --namespace=redis logs -p redis-1-6cp6t
Error from server (BadRequest): previous terminated container "redis" in pod "redis-1-6cp6t" not found
```

**Comment by dtenenba** [comment]
This was my bad. I had forked your repo to run on a local cluster (not in GCE) and in changing the volumes from GCE to PersistentVolumeClaims I failed to specify that the namespace of the PVC should be `redis`. This is fixed now and the pods are now `Running` and not stuck in `ContainerCreating`. 

However, I am still stuck on the first `redis-trib.py` command. After making the fix above to the `console.py` script, I now get this:

```
root@ubuntu:/# redis-trib.py create `dig +short redis-1.redis.svc.cluster.local`:6379     `dig +short redis-2.redis.svc.cluster.local`:6379     `dig +short redis-3.redis.svc.cluster.local`:6379
Redis-trib 0.6.0 Copyright (c) HunanTV Platform developers
INFO:root:Instance at 10.98.168.211:6379 checked
INFO:root:Instance at 10.97.11.128:6379 checked
INFO:root:Instance at 10.103.239.177:6379 checked
Traceback (most recent call last):
  File "/usr/local/bin/redis-trib.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 177, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 28, in create
    command.create([_parse_host_port(hp) for hp in addrs], max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 104, in create
    _add_slots_range(first_conn, 0, first_node_slots, max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 84, in _add_slots_range
    _add_slots(conn, range(begin, end), max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 80, in _add_slots
    addslots(slots_list[i:i + max_slots])
TypeError: sequence index must be integer, not 'slice'
```

It's odd that this script is not working out of the box?

**Comment by dtenenba** [comment]
Incidentally, the issue with redis-trib is resolved if I install version 0.5.1 (0.5.2 and 0.6.0 seem to have issues).

**Comment by matiasinsaurralde** [comment]
Thanks for pointing that out, redis-trib 0.5.1 using Python 2.7, right?

**Comment by dtenenba** [comment]
Yes.

**Comment by dijitali** [comment]
I've reproduced the same issue with the latest redis-trib 0.6.1 release.  0.5.1 seems fine.

Should we raise this as a separate issue over in https://github.com/projecteru/redis-trib.py ?

**Comment by dijitali** [comment]
Another option might be to switch to use `redis-cli` since it now incorporates the cluster management functionality from `redis-trib`:
https://github.com/antirez/redis/blob/5.0/00-RELEASENOTES#L27

However, currently the replicaset uses the `redis:3.2.0-alpine` image which has just dropped out of support with the 5.0 release (this afternoon!).  Can we happily use the new release yet?

**Comment by buger** [comment]
We thinking about moving away from providing own redis scripts, and migrating to standard helm charts like this https://engineering.bitnami.com/articles/deploy-and-scale-a-redis-cluster-on-kubernetes-with-bitnami-and-helm.html

**Comment by leeshd** [comment]
> This was my bad. I had forked your repo to run on a local cluster (not in GCE) and in changing the volumes from GCE to PersistentVolumeClaims I failed to specify that the namespace of the PVC should be `redis`. This is fixed now and the pods are now `Running` and not stuck in `ContainerCreating`.
> 
> However, I am still stuck on the first `redis-trib.py` command. After making the fix above to the `console.py` script, I now get this:
> 
> ```
> root@ubuntu:/# redis-trib.py create `dig +short redis-1.redis.svc.cluster.local`:6379     `dig +short redis-2.redis.svc.cluster.local`:6379     `dig +short redis-3.redis.svc.cluster.local`:6379
> Redis-trib 0.6.0 Copyright (c) HunanTV Platform developers
> INFO:root:Instance at 10.98.168.211:6379 checked
> INFO:root:Instance at 10.97.11.128:6379 checked
> INFO:root:Instance at 10.103.239.177:6379 checked
> Traceback (most recent call last):
>   File "/usr/local/bin/redis-trib.py", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 177, in main
>     cli()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 28, in create
>     command.create([_parse_host_port(hp) for hp in addrs], max_slots)
>   File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 104, in create
>     _add_slots_range(first_conn, 0, first_node_slots, max_slots)
>   File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 84, in _add_slots_range
>     _add_slots(conn, range(begin, end), max_slots)
>   File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 80, in _add_slots
>     addslots(slots_list[i:i + max_slots])
> TypeError: sequence index must be integer, not 'slice'
> ```
> It's odd that this script is not working out of the box?

it's occur from redistrib/command.py , comment '#from six.moves import range" is work fine. 
but why use range by six.moves ??

**Comment by fhqjgd** [comment]
I solved this problem by commenting from six.moves import range under command.py.

**Comment by colinguozizhong** [comment]
I have the same issue in version 0.6.1，and not in version 0.5.1. 
How to Solve the Problem？

root@ubuntu:/# redis-trib.py create `dig +short redis-app-0.redis-service.default.svc.cluster.local`:6379 `dig +short redis-app-1.redis-service.default.svc.cluster.local`:6379 `dig +short redis-app-2.redis-service.default.svc.cluster.local`:6379
Redis-trib 0.6.1 Copyright (c) HunanTV Platform developers
INFO:root:Instance at 10.32.0.7:6379 checked
INFO:root:Instance at 10.32.0.6:6379 checked
INFO:root:Instance at 10.32.0.8:6379 checked
Traceback (most recent call last):
  File "/usr/local/bin/redis-trib.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 181, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/console.py", line 28, in create
    command.create([_parse_host_port(hp) for hp in addrs], max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 104, in create
    _add_slots_range(first_conn, 0, first_node_slots, max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 84, in _add_slots_range
    _add_slots(conn, range(begin, end), max_slots)
  File "/usr/local/lib/python2.7/dist-packages/redistrib/command.py", line 80, in _add_slots
    addslots(slots_list[i:i + max_slots])
TypeError: sequence index must be integer, not 'slice'

**Comment by dijitali** [comment]
@colinguozizhong - I think using redis-trib 0.5.1 (`pip install -I redis-trib==0.5.1`) is the specific fix here but more generally this repo appears to have been deprecated in favour of the Helm chart here: [TykTechnologies/tyk-helm-chart](https://github.com/TykTechnologies/tyk-helm-chart), which suggests using a separate Redis Helm chart.

**Comment by rocketmai** [comment]
> @colinguozizhong - I think using redis-trib 0.5.1 (`pip install -I redis-trib==0.5.1`) is the specific fix here but more generally this repo appears to have been deprecated in favour of the Helm chart here: [TykTechnologies/tyk-helm-chart](https://github.com/TykTechnologies/tyk-helm-chart), which suggests using a separate Redis Helm chart.

Thanks,this has solved the problem.Redis-trib 0.6.1 will occur `TypeError: sequence index must be integer, not 'slice' `, then I do `pip install -I redis-trib==0.5.1`,and then it worked.
```
root@ubuntu:/# redis-trib.py create `dig +short redis-app-0.redis-service.default.svc.cluster.local`:6379  `dig +short redis-app-1.redis-service.default.svc.cluster.local`:6379 `dig +short redis-app-2.redis-service.default.svc.cluster.local`:6379
Redis-trib 0.5.1 Copyright (c) HunanTV Platform developers
INFO:root:Instance at 192.168.226.92:6379 checked
INFO:root:Instance at 192.168.133.223:6379 checked
INFO:root:Instance at 192.168.226.91:6379 checked
INFO:root:Add 5462 slots to 192.168.226.92:6379
INFO:root:Add 5461 slots to 192.168.133.223:6379
INFO:root:Add 5461 slots to 192.168.226.91:6379
root@ubuntu:/# 
```
