### ISSUE TITLE
Tyk dashboad and gateway "No nodes available" 

### ISSUE THREAD

**Issue by smenon78** [TykTechnologies/tyk-kubernetes#2]
Getting  level=error msg="No nodes available" for both dashboard and gateway.

Note:
I have the redis run on standalone mode. 

Tyk analytics config:
apiVersion: v1
kind: ConfigMap
metadata:
  name: tykanalytics-conf
  namespace: default
data:
  tyk_analytics.conf: |-
    {
    "listen_port": 3000,
    "tyk_api_config": {
        "Host": "http://tyk-gateway.default.svc.kubernetes.local",
        "Port": "80",
        "Secret": "352d20ee67be67f6340b4c0605b044b7"
    },
    "mongo_url": "mongodb://mongodb.default.svc.kubernetes.local:27017/tyk_analytics",
    "license_key": "",
    "page_size": 10,
    "admin_secret": "12345",
    "shared_node_secret": "352d20ee67be67f6340b4c0605b044b7",
    "redis_port": 6379,
    "redis_host": "redis.default.svc.kubernetes.local",
    "redis_password": "",
    "enable_cluster": false,
    "force_api_defaults": false,
    "notify_on_change": true,
    "redis_database": 0,
    "hash_keys": true,
    "email_backend": {
        "enable_email_notifications": false,
        "code": "",
        "settings": null,
        "default_from_email": "",
        "default_from_name": ""
    },
    "hide_listen_path": false,
    "sentry_code": "",
    "sentry_js_code": "",
    "use_sentry": false,
    "enable_master_keys": false,
    "enable_duplicate_slugs": true,
    "show_org_id": true,
    "host_config": {
        "enable_host_names": false,
        "disable_org_slug_prefix": true,
        "hostname": "",
        "override_hostname": "www.tyk-portal-test.com",
        "portal_domains": {},
        "portal_root_path": "/portal"
    },
    "http_server_options": {
        "use_ssl": false,
        "certificates": [
            {
                "domain_name": "",
                "cert_file": "",
                "key_file": ""
            }
        ],
        "min_version": 0
    },
    "ui": {
        "login_page": {},
        "nav": {},
        "uptime": {},
        "portal_section": null,
        "designer": {},
        "dont_show_admin_sockets": false,
        "dont_allow_license_management": false,
        "dont_allow_license_management_view": false
    },
    "home_dir": "/opt/tyk-dashboard",
    "identity_broker": {
        "enabled": false,
        "host": {
            "connection_string": "",
            "secret": ""
        }
    },
    "tagging_options": {
        "tag_all_apis_by_org": false
    }
    }

Tyk config:
apiVersion: v1
kind: ReplicationController
metadata:
  name: tyk-gateway
  namespace: default
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: tyk-gateway
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: tyk-gateway
    spec:
      containers:
      - name: tyk-gateway
        image: "{{ tyk_gateway_image }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
          - name: REDIGOCLUSTER_SHARDCOUNT
            value: "128"
        command: ["/opt/tyk-gateway/tyk", "--conf=/etc/tyk-gateway/tyk.conf"]
        workingDir: /opt/tyk-gateway
        ports:
        - containerPort: 8080
          hostPort: 9093
        volumeMounts:
        - mountPath: /etc/tyk-gateway
          name: gateway-conf
      imagePullSecrets:
        - name: docker_repo 
      volumes:
      - name: gateway-conf
        configMap:
          name: tykgateway-conf
---
kind: Service
apiVersion: v1
metadata:
  name: tyk-gateway
  namespace: {{ kube_ns }}
  labels:
    app: tyk-gateway
spec:
  
  ports:
    - name: primary-port
      port: 80
      targetPort: 8080
    - name: secondary-port
      port: 8081
      targetPort: 8080
  selector:
    app: tyk-gateway

Any ideas?

**Comment by matiasinsaurralde** [comment]
Hi, can you share the full logs for Tyk Dashboard, Tyk Gateway and Redis?

**Comment by smenon78** [comment]
I just got it working..It didn't have the license key. Thank you so much for quick response.

**Comment by smenon78** [comment]
I just don't know the username/password to login though. I used the same config file.

**Comment by matiasinsaurralde** [comment]
Did you run the bootstrap script? You will find the credentials there.

**Comment by smenon78** [comment]
I don't see the script in tyk-kubernetes/ repo

**Comment by matiasinsaurralde** [comment]
The script is inside the pod, see the instructions:
```
$ kubectl exec --namespace=tyk tyk-dashboard-1616536863-oeqa2 /opt/tyk-dashboard/install/bootstrap.sh x.x.x.x
```
Where `tyk-dashboard-1616536863-oeqa2` is the pod name (you should replace it with your own) and `x.x.x.x` is your **external IP**.

**Comment by smenon78** [comment]
Oh cool. I need to look more to automate this then so I can set the username/password in bootstrap.sh and run this script on Starting the container.
