### ISSUE TITLE
"tyk-gateway" ReadWriteOnce volume prevents scaling of gateway nodes

### ISSUE THREAD

**Issue by dijitali** [TykTechnologies/tyk-kubernetes#21]
The `tyk-gateway` volume is created as a 10GB `gcePersistentDisk` and mounted as a volume in the gateway container at `/apps`.

Because it's mounted as a ReadWriteOnce volume, the `tyk-gateway` deployment can't be scaled to more than one replica:
```
The Deployment "tyk-gateway" is invalid: spec.template.spec.volumes[0].gcePersistentDisk.readOnly: Invalid value: false: must be true for replicated pods > 1; GCE PD can only be mounted on multiple machines if it is read-only
```

What is the purpose of this volume?  I can only see a single `app_sample.json` file on the volume in my setup.  Can it be mounted as `ReadOnlyMany` to allow multiple nodes to access it or perhaps is a StatefulSet more appropriate?
> Deployments are designed for stateless applications and therefore all replicas of a Deployment share the same Persistent Volume Claim. Since the replica Pods created will be identical to each other, only Volumes with modes ReadOnlyMany or ReadWriteMany can work in this setting.
> 
> Even Deployments with one replica using a ReadWriteOnce Volume are not recommended.
>
> ...
> StatefulSets are the recommended method of deploying stateful applications that require a unique volume per replica. By using StatefulSets with Persistent Volume Claim Templates you can have applications that can scale up automatically with unique Persistent Volume Claims associated to each replica Pod.

https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#deployments_vs_statefulsets

**Comment by matiasinsaurralde** [comment]
Hi, this was originally written for `apps` (file based API definitions) which isn't used when the dashboard is enabled. Feel free to remove it or adjust the mount parameters.

**Comment by dijitali** [comment]
The impression I got is that this entire repo is effectively superseded by [TykTechnologies/tyk-helm-chart](https://github.com/TykTechnologies/tyk-helm-chart).

Presumably the entire repo should just be archived if there's no longer any support here?

**Comment by dijitali** [comment]
Am no longer using this product.
