### ISSUE TITLE
Configure Tyk Identity Broker

### ISSUE THREAD

**Issue by alvarosIGZ** [TykTechnologies/tyk-kubernetes#3]
How can I configure  Tyk Identity Broker in Kubernetes tyk deploy? Is there a deploy about it? Are you planning to dockerize that component?

**Comment by buger** [comment]
Inviting @excieve to discussion :)

**Comment by excieve** [comment]
Unfortunately we don't have a public docker image for it yet but that's definitely something we'd like to do soon. In case you want to try it now, here's a sample of a `Dockerfile` you could try building yourself and making a k8s service with:
```
FROM ubuntu:16.04
RUN mkdir -p /opt/tyk-tib
WORKDIR /opt/tyk-tib
COPY tib .
VOLUME ["/opt/tyk/tyk_sink.conf"]
EXPOSE 3010
ENTRYPOINT ["./tyk-identity-broker"]
```
Here, `tib` directory is an extract of one of the release distributions from here:
https://github.com/TykTechnologies/tyk-identity-broker/releases

**Comment by alvarosIGZ** [comment]
Oh! That's nice, we will try to implement and we will let you know.
As I've reading in the documentation, TIB allows you to log into tyk using external LDAP user. Is that right?

One of our project requirement is to use company's LDAP to login into API Manager. Is that possible using TIB and with TYK deployed in Kubernetes?

Thanks a lot

**Comment by buger** [comment]
@alvarosIGZ exactly! Here are the docs on LDAP https://tyk.io/docs/integrate/3rd-party-identity-providers/openldap/

Basic idea that you will need to build and host your own login form somewhere (with LDAP credentials), which will redirect to URL provided by TIB, query LDAP, and if everything is OK log you to the dashboard.

**Comment by excieve** [comment]
@alvarosIGZ A mistake has slipped in my sample Dockerfile. This:
```
VOLUME ["/opt/tyk/tyk_sink.conf"]
```
should actually be:
```
VOLUME ["/opt/tyk/tib.conf"]
```
Sorry!

**Comment by alvarosIGZ** [comment]
@excieve I'm kind of confused by the following line:
ENTRYPOINT ["./tyk-identity-broker"]

Where is that executable? I've downloaded the release distribution:
https://github.com/TykTechnologies/tyk-identity-broker/releases/download/v0.2/tib-linux-amd64-0.2.tar.gz
There I find an executable file called tyk, but not tyk-identity-broker.

Am I doing something wrong?

Thanks in advance

**Comment by excieve** [comment]
@alvarosIGZ You're right, sorry. This release distribution has a `tib` executable so replacing the entrypoint with the following should do it:
```
ENTRYPOINT ["./tib"]
```

**Comment by alvarosIGZ** [comment]
Hello again! @excieve @buger 
I've been busy with some other stuff but I can take some time to work on this, and I had some doubts...
Where do I have to locate my tib.conf? In which folder?
I'm kind of confused, I don't know if I have to put it in /opt/tyk-tib or in  /opt/tyk/tyk_sink.conf/ folder (because of the volume).

Thanks in advance
