### ISSUE TITLE
Configure developer portal

### ISSUE THREAD

**Issue by alvarosIGZ** [TykTechnologies/tyk-kubernetes#4]
#Hello,
How can I configure developer portal in Kubernetes tyk deploy?
Which is the portal domain for that?
Do I have to have a cname? I'm working with IPs and nodeport in Kubernetes so I don't have any cname available.

Thanks in advance

**Comment by alvarosIGZ** [comment]
any news about this?

**Comment by alvarosIGZ** [comment]
Hello,
So I've managed to get this working by analyzing docker-compose example (https://github.com/TykTechnologies/tyk_quickstart).
Once I've set all kubernetes files (the default ones in this repository) , I can access to the dashboard through {MASTER_IP}:{PORT}/{ORG_ID}/portal... Why do I have to add ORG_ID to the URL? Can I avoid using the ORG_ID for the URL.

Finally I've managed to avoid org id in  the url by creating 3 differents apis:
- Portal
- Portal API
- Portal API Assets

as in the docker example, but I would like to understand why the organization id is part of the url.

**Comment by matiasinsaurralde** [comment]
Hi @alvarosIGZ, the org ID is used for multi-org setups.
Check the domain-related settings here: https://tyk.io/docs/configure/tyk-dashboard-configuration-options/

**Comment by alvarosIGZ** [comment]
Thanks @matiasinsaurralde :) 
So, is it possible to get rid of the orgID setting in some manner the property             "portal_domains": {} ?

**Comment by lakhan361** [comment]
I am running tyk dashboard on kubernetes cluster but not able to access the devloper portal???why??what i should do to resolve it?

**Comment by dijitali** [comment]
@lakhan361 - I believe you need to include the Organisation ID in the URL.  

So if you access your Dashboard at: `http://10.20.30.40:3000/#/`
Then your Developer Portal should be available here: `http://10.20.30.40:3000/<ORG-ID>/portal/`

You can see your Organisation ID at the bottom of the "Edit Profile" page from the Dashboard. 

I'm not sure why this is required or how it would be configured (especially as the "Open Your Portal" link from the dashboard doesn't add your org ID in for you).  

The documentation mentions a `host_config.portal_domains` setting, but I'm not quite sure what it's overriding exactly.  I think it may allow you to map different Org IDs to different CNAMEs for the Portal.

---

Bit of feedback for @TykTeam - a completely populated basic example configuration for each Tyk component would be really useful from a getting started perspective!  Similar to you had here (now out-dated): https://tyk.io/blog/docs/tyk-identity-broker/social-examples/

**Comment by dijitali** [comment]
I think this was resolved for me by setting the `host_config:enable_host_names` option to `true` and then applying a CNAME through the Dashboard "Set your portal domain" option.

It would be great if this could be the default setup or explained clearly.  The documentation states that this option is "not recommended" but it appears to be required for this functionality?

> `host_config.enable_host_names`: Tyk Dashboard can bind the Dashboard application to a specific domain name, enable this option to have Tyk Dashboard only allow access on a specific domain and 404 on any other host access (not recommended).

**Comment by ilijabojanovic** [comment]
@dijitali Thanks for feedback, i we created PR for config updates. Also we will improve documentation.
