### ISSUE TITLE
Portal Not Found

### ISSUE THREAD

**Issue by albertoig** [TykTechnologies/tyk-kubernetes#5]
I had to configure the cname with a reverse proxy to do it, i use a kubernetes with node port configuration, it's imposible to reserve port 3000 or 80. I modify the bootstrap.sh to point to port 32000, the dashboard  and gateway are working fine but the portal give us this message. Why the portal could give us this message?

**Comment by ConsM** [comment]
Have you followed any of our guides ? Such as [this](https://tyk.io/docs/publish/tutorials/publish-api-developer-portal/).
There's also a troubleshooting section [here](https://tyk.io/docs/troubleshooting/tyk-dashboard/not-found-error-developer-portal/).

**Comment by albertoig** [comment]
Yes, i tried and i have the same message in http://myurl/portal

**Comment by ConsM** [comment]
Ok, can you share your `tyk_analytics.conf` ?

**Comment by albertoig** [comment]
Finaly we resolve it with the gateway. Doing a bypass between gateway and the portal

**Comment by joshblakeley** [comment]
Closing issue as solved
